# -*- coding: utf-8 -*-
"""mongo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p_Z7_keg_5ngtxpDGOg71a2T5FyA6PNF
"""

!pip install dnspython

import pymongo
import pandas as pd
import json

myclient = pymongo.MongoClient("mongodb+srv://hugo:senha123@cluster0-uln1j.mongodb.net/test?retryWrites=true&w=majority")

db = myclient.ovni
collection = db.ovnis

df = pd.read_csv('df_OVNI_preparado.csv')

df_json = df.to_json(orient='records')

json_ovni = json.loads(df_json)

inserir = collection.insert_many(json_ovni)
lista = list(collection.find({}))

contar = collection.count_documents({})

resgate = collection.find().sort("shape")
list(resgate)

ocorrencia = list(collection.aggregate([{'$group': {'Views': {'$sum': 1},
'_id': '$State'}}, {'$sort': {'views': -1}}]))

phoenix = list(collection.find({'City' : 'Phoenix'}))

cali = list(collection.find({'City' : 'Phoenix'}, {'_id': 0}))