# -*- coding: utf-8 -*-
"""projeto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jBCblCjXNwy_FjSE-UbKBM0l5_GKg-BC
"""

#!pip install beautifulsoup4
#!pip install lxml
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

link = 'http://www.nuforc.org/webreports/ndxe'
final ='.html'

df_1 = []
c=0
for i in range(1997,2018):
  mes = ['01','02','03','04','05','06','07','08','09','10','11','12']
  if(i==1998):  
    mes = ['01','02','03','04','05','06','07','08','09']
  if(i==1997):
    mes = ['10','11','12']
  for j in mes:
    url_it = requests.get('{0}{1}{2}{3}'.format(link,i,j,final))
    soup = BeautifulSoup(url_it.content, 'html.parser').find('table')
    df = pd.read_html(str(soup))[0]
    df_1.append(df)    
    time.sleep(1)
    

df_2 = pd.concat(df_1, ignore_index=True)
df_2.to_csv('OvNi.csv',index=False)

#     rr = requests.get(url_it)
#     print(rr)
#     lista_r = BeautifulSoup(rr.text, 'html.parser')
#     lista_link2 = lista_r.find_all('table')
#     print(lista_link2)
#     df = pd.read_html(lista_link2)
    
#     print(df)

