# -*- coding: utf-8 -*-
"""5.7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xa8UwSxm8dDLl3hdUKwvPBg14T3I1C-1
"""

!pip install -U pandasql

import pandas as pd
import pandasql

ovini = pd.read_csv('OVNIS.csv')

remover = """
SELECT * FROM OV WHERE lower(City) not in ('unknown', 'none', ' ') and  
lower(State) not in ('unknown', 'none', ' ') and lower(Shape) not in ('unknown', 'none', ' ')
 """
  
ovini_filtrado = pandasql.sqldf(remover)

estados = pd.read_csv('states.csv')

sql_estados = '''
  SELECT ovini_filtrado.* FROM ovini_filtrado, estados
  WHERE ovini_filtrado.State = estados.Abbreviation
'''

filtro_estados = pandasql.sqldf(sql_estados)

ovni_remove_var = filtro_estados.drop(['Duration', 'Summary', 'Posted'],axis=1)

mil_shape = '''
  SELECT Shape, COUNT(Shape) as Ocorrencia FROM ovni_remove_var  
  GROUP BY Shape HAVING Ocorrencia > 1000 
'''

filtro_shape = pandasql.sqldf(mil_shape)

filtro_ovni = '''
  SELECT ovni_remove_var.* FROM ovni_remove_var, filtro_shape
  WHERE filtro_shape.Shape = ovni_remove_var.Shape
'''

ovni_df = pandasql.sqldf(filtro_ovni)

ovni_df.to_csv('df_OVNI_limpo.csv')

new_ovni = pd.read_csv('df_OVNI_limpo.csv')