# -*- coding: utf-8 -*-
"""5.8 - Acréscimo de variáveis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1owLkFfwiwZHRBKvHyjLyzZBBRXdDpc8V
"""



# !pip install -U pandasql

import pandas as pd
import pandasql

"""###Carregando o arquivo e deletando a coluna que restou da atividade passada:"""

df = pd.read_csv('df_OVNI_limpo.csv')
del df['Unnamed: 0']

"""###Dividindo o conteúdo da coluna Date / Time em duas novas colunas no mesmo dataframe."""

df_dt = pd.to_datetime(df['Date / Time'])

hr = df_dt.dt.strftime('%H:%M')
dt = df_dt.dt.strftime('%d/%m/%y')
df['Sight_Date'] = dt
df['Sight_Time'] = hr

"""###Deletando a coluna Date / Time ."""

del df['Date / Time']

"""###Criando a coluna com os dias da semana (numeral)"""

dias_semana = pd.to_datetime(df['Sight_Date']).dt.weekday
df['Sight_Weekday'] = dias_semana

"""###Crindo uma lista para substituir os números em texto"""

dias = {
    0: 'Segunda-Feira',
    1: 'Terça-Feira',
    2: 'Quarta-Feira',
    3: 'Quinta-Feira',
    4: 'Sexta-Feira',
    5: 'Sábado',
    6: 'Domingo'
}

"""###Substituindo os números pelo texto"""

dias_col = [dias[i] for i in list(df['Sight_Weekday'])]
df['Sight_Weekday'] = dias_col

"""###Adicionando as duas novas colunas (Dia e mês)"""

dia = df_dt.dt.strftime('%d')
mes = df_dt.dt.strftime('%m')
df['Sight_Day'] = dia
df['Sight_Month'] = mes

"""###salvando o dataframe resultante em um novo arquivo CSV."""

df.to_csv('df_OVNI_preparado.csv')